Implement PowerQuery support for SentinelOne
redcanaryco/surveyor pull request #94
Opened 2023-01-20 23:19 UTC by jholtmann

This PR implements PowerQuery support for the SentinelOne product. 

**Benefits of PowerQuery (PQ) over Deep Visibility (DV):**
- Lack of a 1req/min rate limit allows a product to perform a separate query per search criteria, resulting in more useful output
- Ability to perform a query per search criteria helps reduce the impact of the 20k search result limit

**Discussion Points:**
- Which mode should be the default, PQ or DV? PQ provides faster and more accurate search results, but I am not sure if it is available across all S1 consoles. This PR currently sets PQ as the default and allows falling back to DV with the `--dv` product flag.
- PQ does not respect Site ID filters unless the parent Account ID is also included in the query. This means that if the user provides both an Account ID and a nested Site ID, we cannot assume that only the Account ID should be queried (as we currently do in DV mode). This PR automatically adds the Account ID when only a Site ID is provided by the user. This logic difference between DV and PQ may be confusing to users.
- Having both PQ and DV implementations makes the code somewhat harder to understand due to frequent branching logic. If we determine that PowerQuery can be assumed to be globally available, we may want to consider removing DV support in the future.

**Testing:**
- I have tested PQ and DV searches with various definition files and haven't noticed any issues.

2023-02-23 15:49 UTC, rc-csmith requested changes
Just a few changes since I came across a couple bugs. Otherwise, works like a charm and is so much better than DV!!

2023-02-23 15:49 UTC, rc-csmith commented on products/sentinel_one.py
> +                    query_text.append((tag, full_query))
When I only specify the `--query` param and don't use definition files, the query isn't built correctly

```suggestion
                    if query.full_query is not None:
                        query_text.append((tag, query.full_query))
                    else:
                        full_query = f'{query.parameter} {query.operator} {query.search_value}'
                        query_text.append((tag, full_query))
```

Error log:
```
[2023-02-23 09:14:38,187] [DEBUG   ] [surveyor.s1                         ] [common.py           :54  ] Authenticated
[2023-02-23 09:14:38,189] [DEBUG   ] [surveyor                            ] [help.py             :36  ] Running Custom Query: src.process.name contains "svchost.exe"
[2023-02-23 09:14:38,189] [DEBUG   ] [surveyor.s1                         ] [help.py             :36  ] Built Query: src.process.name contains "svchost.exe"
[2023-02-23 09:14:38,189] [DEBUG   ] [surveyor.s1                         ] [sentinel_one.py     :713 ] Entered get_results
[2023-02-23 09:14:38,189] [DEBUG   ] [surveyor.s1                         ] [sentinel_one.py     :717 ] Executing additional _process_queries
[2023-02-23 09:14:38,190] [DEBUG   ] [surveyor.s1                         ] [sentinel_one.py     :564 ] Query params: {'accountIds': ['REDACTED'], 'fromDate': 1677163478189, 'toDate': 1677165278189, 'limit': 20000, 'query': 'None None None | group count() by endpoint.name, src.process.user, src.process.image.path, src.process.cmdline, src.process.name, src.process.publisher, url.address, tgt.file.internalName, event.time, site.id, site.name'}
```

2023-02-23 15:49 UTC, rc-csmith commented on products/sentinel_one.py
> +            events = self._get_dv_events(query_id, p_bar=p_bar, cancel_event=cancel_event)
When testing, I came across this issue when the script checked the status of a PowerQuery, 503 errors got thrown regardless of if the query is valid or if there's results being returned. Adding this section appeared to clear up the errors. I'm wondering if the API doesn't allow you to ping a PowerQuery's status if the search is finished in the initial call?

```suggestion
            if self._pq and body['data']['status'] == 'FINISHED': # If using PQ, the results can be returned immediately
                events = body['data']['data']
            else:
                events = self._get_dv_events(query_id, p_bar=p_bar, cancel_event=cancel_event)
```

2023-02-27 22:04 UTC, xC0uNt3r7hr34t commented
PowerQuery is still in Beta. I would recommend that DV be set to default until PowerQuery is released to GA and more stable. I agree with all the other benefits. If we want to keep PowerQuery as the default for the future to limit code changes, then we need to make it very obvious in documentation and help guide that PowerQuery is default.

2023-03-22 14:55 UTC, rc-csmith commented
Because of the benefits of using PQ (more accurate results and faster runtime), I think we should go ahead and keep it as defaul. But, as @xC0uNt3r7hr34t said, we'll need to make sure documentation and release notes are in place when the changes go live so users are aware.

2023-03-23 14:38 UTC, merged